### ISSUE TITLE
Allow multiple template folders

### ISSUE THREAD

**Issue by thomasraynal** [BeezUP/dotnet-codegen#3]
Currently, we need to provide one, and one only template folder when applying templates.
Could we update it to multiple folders?

Uses cases would be template folder logical division in a project, or a third party tool build on top of code-gen allowing template extensibility for its users (i.e ./third-party-app-templates and ./third-party-app user-templates)

What do you think?

I pertinent, I will of course do the PR.

**Comment by jrouaix** [comment]
Well I like the idea a lot ! Could also allow some override rules to allow one user template to completely rewrite one of the "community" template

**Comment by thomasraynal** [comment]
https://github.com/BeezUP/dotnet-codegen/pull/5
