### ISSUE TITLE
Allow dynamic helper registration

### ISSUE THREAD

**Issue by thomasraynal** [BeezUP/dotnet-codegen#4]
Not being able to dynamically register helpers is a serious drawback and we lose a lot of the initial flexibility handlebars provide as a template engine. 

Maybe it would be a good idea to allow a range of assemblies as command line argument to add to the registration process assembly scanning? 

Of course, dynamic assembly loading is always a tricky feature to secure: dependencies, .NET version etc... But it would at least leave a door open.

What do you think?

**Comment by jrouaix** [comment]
I think a lot of good, I don't know yet the way will pick to do that but it's definitely something we'll need in order for others to use this project without having to fork it.

**Comment by jrouaix** [comment]
Here is a first version : https://github.com/BeezUP/dotnet-codegen/commit/4c8cb1f82d98acba3de71b7eefc08f5decfe9b76
available in version 0.7 with `-c` flag
